### ISSUE TITLE
How to build/install this extension?

### ISSUE THREAD

**Issue by marvinbernhardt** [geekprojects/nuTensor#5]
**Is your feature request related to a problem? Please describe.**
I don't know how to install it.

**Describe the solution you'd like**
A brief build/installation instruction in the Readme.

**Describe alternatives you've considered**
Looked for nuTensor in AMO, but no luck. Will it be in their at same point?

**Comment by DrFlibble** [comment]
Thanks for the feedback, I'll add some instructions to the README.

I haven't yet released it to AMO, but I will do at some point. I was hoping to make more tweaks/changes/fixes before releasing.

**Comment by DrFlibble** [comment]
I've added some basic instructions in doc/BUILDING.md. The installation instructions are in doc/README.md.

**Comment by marvinbernhardt** [comment]
Awesome, thank you!

**Comment by MPeti1** [comment]
I fail to find the mentioned .xpi file on the releases page, but the instruction still points to them. How can one download the compiled plugin currently?

**Comment by jtagcat** [comment]
please google, this is the reason umatrix was abandoned

xpi is a zip, that happens to contain an extension

**Comment by MPeti1** [comment]
I know that xpi's are basically a zip file, but zhis zip can't be loaded as a plugin, because Firefox says that the file is corrupt. It's not wrong, though, because even it's structure differs from the structure of actual plugin xpi files: xpi files have the source files in the root of the archive, but the zip that you can download has a directory in it, which has the src directory, in which are the source files. Firefox does not search for the sources there, but outside of the outmost directory

The zip files in the releases section are not plugin files, they are just the archives of the source code at the time of releasing the version. The proof of it is that the released zip file contains the git repo (.git directory), docs, tools, readme and other files that are usually not released in xpi files.

Further, I don't think uMatrix was abandoned because they didn't provide the plugin in an accessible form. It was abandoned because the author didn't have enough time to maintain both this and uBO. please google, so you will know it too
